spring:
  application:
    name: GameSite

server:
  port: 8080
  compression:
    enabled: true
  error:
    path: "/pages/PageNotFound"

  allowedOrigins: http://localhost:8080, http://localhost:4200, null, http://localhost:3000

endpoints:
  frontendPrefix: ""
  socket: socket
  stomp: stomp

userActivityTimeoutSeconds: 3600
cacheClearIntervalSeconds: 1800

allowed-users-file: ./UsersFile-dev.json