spring:
  application:
    name: GameSite

server:
  port: 8080
  compression:
    enabled: true
  error:
    path: "/pages/PageNotFound"

  allowedOrigins: http://localhost:8080, http://localhost:4200, null

endpoints:
  frontendPrefix: pages
  socket: socket
  stomp: stomp

database:
  leaderboardName: leaderboard_qa
  gameHist: game_hist_qa