spring:
  application:
    name: GameSite

server:
  port: 8080
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false

  allowedOrigins: http://localhost:8080, http://localhost:4200, null, http://localhost:3000

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include:
          - httptrace
  httpexchanges:
    recording:
      enabled: true

endpoints:
  socket: socket
  stomp: stomp

auth:
  cookieIdBuffer: 3
  userActivityTimeoutSeconds: 3600
  cacheClearIntervalSeconds: 1800

  private_key: classpath:/exclude-from-build/privatekey.key
  public_key: classpath:/exclude-from-build/publickey.crt
  allowed-users-file: classpath:/exclude-from-build/UsersFile-dev.json