package me.dulce.gamesite.gamesite2.Database;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "leaderboard_prod")
public class Player {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private int id;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private int rank;

    @DynamoDBAttribute
    private int NoGamesWon;


    public int getId() {        return id;
    }


    public String getName() {
        return name;
    }

    public int getRank() {
        return rank;
    }

}
