/**
 * Gamesite Backend
 * Gamesite backend rest api
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RoomListing { 
    roomId: string;
    lobbySize: number;
    maxLobbySize: number;
    spectatorsAmount: number;
    gameId: string;
    hostName: string;
    inProgress: boolean;
    gameStartTime?: Date;
    roomName: string;
}